### PR TITLE
remove .pyc files from source control

### PR DESCRIPTION
**Pull request by tfdavids-zz**

### CODE REVIEW

**Comment by tfdavids-zz** [comment]
`.pyc` files are compiled Python binaries. As long as we have the `.py` files we have everything we need to recreate the environment -- the `.pyc` files aren't necessary and shouldn't be included in source control.

**Comment by austinschleder** [comment]
ah cool. i assume they were included because i just do “git add .”

so now you can add them to .gitignore and they won’t be updated every time i do “git add .” or should i change to “git add file1.py file2.html file3.csv” from now on?

**Comment by tfdavids-zz** [comment]
Nope, as long as you include them in `.gitignore` you can still do a `git
add .` and you won't add them. It's good to check what you are adding,
though, just in case you end up with files you weren't expecting.

**Comment by tfdavids-zz** [comment]
Hooray!

**Comment by austinschleder** [comment]
wooo!

**Pull request merged**
